openapi: 3.0.0
info:
  title: "FLASK WEB API REST"
  description: "AN API ABOUT PERSON AND NOTE"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Person:
      type: "object"
      required:
        - lname
      properties:
        fname:
          type: "string"
        lname:
          type: "string"

  parameters:
    lname:
      name: "lname"
      description: "Last name of a person to get"
      in: path
      required: True
      schema:
        type: "string"
    note_id:
      name: "note_id"
      description: "ID of the note"
      in: path
      required: True
      schema:
        type: "integer"

paths:
  /people:
    get:
      operationId: "people.read_all"
      tags:
        - "People"
      summary: "Read the list of the people"
      responses:
        "200":
          description: "Succesfully read people list"

    post:
      operationId: "people.create"
      tags:
        - "People"
      summary: "Create a people"
      requestBody:
        description: "Person to create"
        required: True
        content:
          application/json:
            schema:
              #x-body-name: "person"
              $ref: "#/components/schemas/Person"
        x-body-name: "person"
      responses:
        "201":
          description: "Succesfully create person"

  /people/{lname}:
    get:
      operationId: "people.read_one"
      tags:
        - People
      summary: "Read one person"
      parameters:
        - $ref: "#/components/parameters/lname"
      responses:
        "200":
          description: "Successfully read person"
    put:
      tags:
        - People
      operationId: "people.update"
      summary: "Update a person"
      parameters:
        - $ref: "#/components/parameters/lname"
      responses:
        "200":
          description: "Successfully updated person"
      requestBody:
        content:
          application/json:
            schema:
              #x-body-name: "person"
              $ref: "#/components/schemas/Person"
        x-body-name: "person"
    delete:
      tags:
        - People
      operationId: "people.delete"
      summary: "Delete a person"
      parameters:
        - $ref: "#/components/parameters/lname"
      responses:
        "204":
          description: "Successfully deleted a person"

  /notes:
    post:
      operationId: "notes.create"
      tags:
        - Notes
      summary: "Create a note associated with person"
      requestBody:
        description: "Note to create"
        required: True
        content:
          application/json:
            schema:
              type: "object"
              properties:
                person_id:
                  type: "integer"
                content:
                  type: "string"
        x-body-name: "note"
      responses:
        "201":
          description: "Successfully create a note"

  /notes/{note_id}:
    get:
      operationId: "notes.read_one"
      tags:
        - Notes
      summary: "Read one note"
      parameters:
        - $ref: "#/components/parameters/note_id"
      responses:
        "200":
          description: "Successfully read one note"

    put:
      operationId: "notes.update"
      tags:
        - Notes
      summary: "Update et note"
      parameters:
        - $ref: "#/components/parameters/note_id"
      responses:
        "201":
          description: "Successfully updated a note"
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: "note"
              type: object
              properties:
                content:
                  type: "string"

    delete:
      operationId: "notes.delete"
      tags:
        - Notes
      summary: "Delete a note"
      parameters:
        - $ref: "#/components/parameters/note_id"
      responses:
        "204":
          description: "Successfully deleted a note"






















